POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "test",
    "name": "even more test",
    "password": "youcantseeme",
    "id": "642b2134f28bed42d3598f2d"
}